# -*- coding: utf-8 -*-
"""NN for Power

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/CoderJeel/8317509ee4a281668280e2090f3be844/nn-for-power.ipynb
"""

from google.colab import files
file = files.upload()

import pandas as pd
df = pd.read_csv('Data For NN.csv')

df.head()

df.shape

df_1 = df.rename(columns={"Wind Speed (m/s)":"wind Speed","Theoretical_Power_Curve (KWh)":"power","Wind Direction (°)":"wind dir"})

y = df.iloc[:,1:-1]
df_1 = df.drop(columns='Theoretical_Power_Curve (KWh)')
x = df_1.iloc[:,:]

y.shape

from sklearn.model_selection import train_test_split
x_train,y_train,x_test,y_test = train_test_split(x,y,test_size=0.2)

y_train.shape

from keras.models import Sequential
from keras.layers import Dense
regressor = Sequential()
regressor.add(Dense(units=64,activation='relu',input_dim=2))
regressor.add(Dense(units=5,activation='relu'))
regressor.add(Dense(units=3,activation='relu'))
regressor.add(Dense(units=1))

regressor.optimizers.SGD(lr=0.01, nesterov=True)

regressor.compile(loss='mse',optimizer='Adam')

regressor.fit(x,y,batch_size=2,epochs=20)

regressor.save("model.h5")

from keras.models import load_model
regressor = load_model("model.h5")

import requests
import json

respon = requests.get('https://api.openweathermap.org/data/2.5/onecall?lat=22.25&lon=71.19&%20exclude=houly&appid=2be1dca4896e5b73df449f2570ee7c29')

respon_json = respon.json()

data = respon_json['hourly']
#df_2 = pd.DataFrame(respon_json)

df_2 = pd.DataFrame(data)

df_2.drop(columns='weather')

temp = df_2['wind_speed']
temp.append(df_2['wind_deg'])
temp

test_data = df_2.loc[:,['wind_speed','wind_deg']]

import datetime
print(
    datetime.datetime.fromtimestamp(
        int("1592575200")
    ).strftime('%Y-%m-%d %H:%M:%S')
)

regressor.predict(test_data)